/*
 * Conversation API | Sinch
 *
 * OpenAPI document version: 1.0
 * Contact: support@sinch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package com.sinch.sdk.domains.conversation.models.v1.contacts.response;

import com.sinch.sdk.core.http.HttpRequest;
import com.sinch.sdk.core.models.pagination.ListResponse;
import com.sinch.sdk.core.models.pagination.Page;
import java.util.Collection;
import java.util.Collections;
import java.util.NoSuchElementException;
import java.util.function.Supplier;

/** Auto paginated response for list of IdentityConflicts */
public class IdentityConflictsListResponse extends ListResponse<IdentityConflicts> {

  private final Page<IdentityConflicts, HttpRequest> page;
  private final Supplier<IdentityConflictsListResponse> supplier;

  public IdentityConflictsListResponse(
      Supplier<IdentityConflictsListResponse> supplier, Page<IdentityConflicts, HttpRequest> page) {
    this.supplier = supplier;
    this.page = page;
  }

  @Override
  public boolean hasNextPage() {
    if (null == page.getNextPageToken() || null == getContent() || getContent().isEmpty()) {
      return false;
    }
    return true;
  }

  @Override
  public IdentityConflictsListResponse nextPage() {
    if (!hasNextPage()) {
      throw new NoSuchElementException("Reached the last page of the API response");
    }
    return supplier.get();
  }

  @Override
  public Collection<IdentityConflicts> getContent() {
    return page == null ? Collections.emptyList() : page.getEntities();
  }

  @Override
  public String toString() {
    return "IdentityConflictsListResponse {" + "page=" + page + '}';
  }
}
