/*
 * API Overview | Sinch
 *
 * OpenAPI document version: v1
 * Contact: Support@sinch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package com.sinch.sdk.domains.sms.models.v1.batches.request;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.sinch.sdk.core.utils.EnumDynamic;
import com.sinch.sdk.core.utils.EnumSupportDynamic;
import com.sinch.sdk.domains.sms.models.v1.batches.DeliveryReportType;
import java.time.Instant;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Stream;

/** BinaryRequest */
@JsonDeserialize(builder = BinaryRequestImpl.Builder.class)
public interface BinaryRequest extends BatchRequest {

  /**
   * A list of phone numbers and group IDs that will receive the batch. <a
   * href="https://community.sinch.com/t5/Glossary/MSISDN/ta-p/7628">More info</a>.
   *
   * @return to
   */
  List<String> getTo();

  /**
   * Sender number. Must be valid phone number, short code or alphanumeric. Required if Automatic
   * Default Originator not configured.
   *
   * @return from
   */
  String getFrom();

  /**
   * The message content Base64 encoded. Max 140 bytes including <code>udh</code>.
   *
   * @return body
   */
  String getBody();

  /**
   * The UDH header of a binary message HEX encoded. Max 140 bytes including the <code>body</code>.
   *
   * @return udh
   */
  String getUdh();

  /**
   * SMS in <a href="https://community.sinch.com/t5/Glossary/Binary-SMS/ta-p/7470">binary</a>
   * format.
   */
  public class TypeEnum extends EnumDynamic<String, TypeEnum> {
    public static final TypeEnum MT_BINARY = new TypeEnum("mt_binary");

    private static final EnumSupportDynamic<String, TypeEnum> ENUM_SUPPORT =
        new EnumSupportDynamic<>(TypeEnum.class, TypeEnum::new, Arrays.asList(MT_BINARY));

    private TypeEnum(String value) {
      super(value);
    }

    public static Stream<TypeEnum> values() {
      return ENUM_SUPPORT.values();
    }

    public static TypeEnum from(String value) {
      return ENUM_SUPPORT.from(value);
    }

    public static String valueOf(TypeEnum e) {
      return ENUM_SUPPORT.valueOf(e);
    }
  }

  /**
   * Get deliveryReport
   *
   * @return deliveryReport
   */
  DeliveryReportType getDeliveryReport();

  /**
   * If set in the future the message will be delayed until <code>send_at</code> occurs. Must be
   * before <code>expire_at</code>. If set in the past, messages will be sent immediately. Formatted
   * as <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO-8601</a>. For example: <code>
   * YYYY-MM-DDThh:mm:ss.SSSZ</code>.
   *
   * @return sendAt
   */
  Instant getSendAt();

  /**
   * If set, the system will stop trying to deliver the message at this point. Must be after <code>
   * send_at</code>. Default and max is 3 days after <code>send_at</code>. Formatted as <a
   * href="https://en.wikipedia.org/wiki/ISO_8601">ISO-8601</a>. For example: <code>
   * YYYY-MM-DDThh:mm:ss.SSSZ</code>.
   *
   * @return expireAt
   */
  Instant getExpireAt();

  /**
   * Override the <em>default</em> callback URL for this batch. Must be a valid URL. Learn how to
   * set a default callback URL <a
   * href="https://community.sinch.com/t5/SMS/How-do-I-assign-a-callback-URL-to-an-SMS-service-plan/ta-p/8414">here</a>.
   *
   * @return callbackUrl
   */
  String getCallbackUrl();

  /**
   * The client identifier of a batch message. If set, the identifier will be added in the delivery
   * report/callback of this batch.
   *
   * @return clientReference
   */
  String getClientReference();

  /**
   * If set to true then <a
   * href="/docs/sms/api-reference/sms/tag/Batches/#tag/Batches/operation/deliveryFeedback">feedback</a>
   * is expected after successful delivery.
   *
   * @return feedbackEnabled
   */
  Boolean getFeedbackEnabled();

  /**
   * The type of number for the sender number. Use to override the automatic detection.
   *
   * <p>minimum: 0 maximum: 6
   *
   * @return fromTon
   */
  Integer getFromTon();

  /**
   * Number Plan Indicator for the sender number. Use to override the automatic detection.
   *
   * <p>minimum: 0 maximum: 18
   *
   * @return fromNpi
   */
  Integer getFromNpi();

  /**
   * Getting builder
   *
   * @return New Builder instance
   */
  static Builder builder() {
    return new BinaryRequestImpl.Builder();
  }

  /** Dedicated Builder */
  interface Builder {

    /**
     * see getter
     *
     * @param to see getter
     * @return Current builder
     * @see #getTo
     */
    Builder setTo(List<String> to);

    /**
     * see getter
     *
     * @param from see getter
     * @return Current builder
     * @see #getFrom
     */
    Builder setFrom(String from);

    /**
     * see getter
     *
     * @param body see getter
     * @return Current builder
     * @see #getBody
     */
    Builder setBody(String body);

    /**
     * see getter
     *
     * @param udh see getter
     * @return Current builder
     * @see #getUdh
     */
    Builder setUdh(String udh);

    /**
     * see getter
     *
     * @param deliveryReport see getter
     * @return Current builder
     * @see #getDeliveryReport
     */
    Builder setDeliveryReport(DeliveryReportType deliveryReport);

    /**
     * see getter
     *
     * @param sendAt see getter
     * @return Current builder
     * @see #getSendAt
     */
    Builder setSendAt(Instant sendAt);

    /**
     * see getter
     *
     * @param expireAt see getter
     * @return Current builder
     * @see #getExpireAt
     */
    Builder setExpireAt(Instant expireAt);

    /**
     * see getter
     *
     * @param callbackUrl see getter
     * @return Current builder
     * @see #getCallbackUrl
     */
    Builder setCallbackUrl(String callbackUrl);

    /**
     * see getter
     *
     * @param clientReference see getter
     * @return Current builder
     * @see #getClientReference
     */
    Builder setClientReference(String clientReference);

    /**
     * see getter
     *
     * @param feedbackEnabled see getter
     * @return Current builder
     * @see #getFeedbackEnabled
     */
    Builder setFeedbackEnabled(Boolean feedbackEnabled);

    /**
     * see getter
     *
     * @param fromTon see getter
     * @return Current builder
     * @see #getFromTon
     */
    Builder setFromTon(Integer fromTon);

    /**
     * see getter
     *
     * @param fromNpi see getter
     * @return Current builder
     * @see #getFromNpi
     */
    Builder setFromNpi(Integer fromNpi);

    /**
     * Create instance
     *
     * @return The instance build with current builder values
     */
    BinaryRequest build();
  }
}
