/*
 * Numbers | Sinch
 * An API service for getting, listing and managing Sinch virtual numbers.
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: Support@sinch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sinch.sdk.domains.numbers.models.v1;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * The current SMS configuration for this number. Once the <code>servicePlanId</code> is sent, it
 * enters scheduled provisioning. The status of scheduled provisioning will show under a <code>
 * scheduledProvisioning</code> object if it's still running. Once processed successfully, the
 * <code>servicePlanId</code> sent will appear directly under the <code>smsConfiguration</code>
 * object.
 */
@JsonDeserialize(builder = SmsConfigurationImpl.Builder.class)
public interface SmsConfiguration {

  /**
   * The <code>servicePlanId</code> can be found in the <a
   * href="https://dashboard.sinch.com/sms/api/rest">Sinch Customer Dashboard</a>. The service plan
   * ID is what ties this number to the configured SMS service.
   *
   * @return servicePlanId
   */
  String getServicePlanId();

  /**
   * Only for US virtual numbers. This campaign ID relates to <a
   * href="https://community.sinch.com/t5/10DLC/What-is-10DLC/ta-p/7845">10DLC numbers</a>. So, it
   * is the current campaign ID for this number. The <code>campaignId</code> is found on your TCR
   * platform.
   *
   * @return campaignId
   */
  String getCampaignId();

  /**
   * Get scheduledProvisioning
   *
   * @return scheduledProvisioning
   */
  ScheduledSmsProvisioning getScheduledProvisioning();

  /**
   * Getting builder
   *
   * @return New Builder instance
   */
  static Builder builder() {
    return new SmsConfigurationImpl.Builder();
  }

  /** Dedicated Builder */
  interface Builder {

    /**
     * see getter
     *
     * @param servicePlanId see getter
     * @return Current builder
     * @see #getServicePlanId
     */
    Builder setServicePlanId(String servicePlanId);

    /**
     * see getter
     *
     * @param campaignId see getter
     * @return Current builder
     * @see #getCampaignId
     */
    Builder setCampaignId(String campaignId);

    /**
     * see getter
     *
     * @param scheduledProvisioning see getter
     * @return Current builder
     * @see #getScheduledProvisioning
     */
    Builder setScheduledProvisioning(ScheduledSmsProvisioning scheduledProvisioning);

    /**
     * Create instance
     *
     * @return The instance build with current builder values
     */
    SmsConfiguration build();
  }
}
