/*
 * Conversation API | Sinch
 *
 * OpenAPI document version: 1.0
 * Contact: support@sinch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package com.sinch.sdk.domains.conversation.models.v1.events.request;

import com.sinch.sdk.core.models.OptionalValue;

/** EventsListQueryParameters */
public interface EventsListQueryParameters {

  /**
   * Get conversationId
   *
   * @return conversationId
   */
  OptionalValue<String> getConversationId();

  /**
   * Get contactId
   *
   * @return contactId
   */
  OptionalValue<String> getContactId();

  /**
   * Get pageSize
   *
   * @return pageSize
   */
  OptionalValue<Integer> getPageSize();

  /**
   * Get pageToken
   *
   * @return pageToken
   */
  OptionalValue<String> getPageToken();

  /**
   * Getting builder
   *
   * @return New Builder instance
   */
  static Builder builder() {
    return new EventsListQueryParametersImpl.Builder();
  }

  /**
   * Getting builder from existing instance
   *
   * @return New Builder instance
   */
  static Builder builder(EventsListQueryParameters parameters) {
    return new EventsListQueryParametersImpl.Builder(parameters);
  }

  /** Dedicated Builder */
  interface Builder {

    /**
     * see getter
     *
     * @param conversationId see getter
     * @return Current builder
     * @see #getConversationId
     */
    Builder setConversationId(String conversationId);

    /**
     * see getter
     *
     * @param contactId see getter
     * @return Current builder
     * @see #getContactId
     */
    Builder setContactId(String contactId);

    /**
     * see getter
     *
     * @param pageSize see getter
     * @return Current builder
     * @see #getPageSize
     */
    Builder setPageSize(Integer pageSize);

    /**
     * see getter
     *
     * @param pageToken see getter
     * @return Current builder
     * @see #getPageToken
     */
    Builder setPageToken(String pageToken);

    /**
     * Create instance
     *
     * @return The instance build with current builder values
     */
    EventsListQueryParameters build();
  }
}
