/*
 * Conversation API | Sinch
 *
 * OpenAPI document version: 1.0
 * Contact: support@sinch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package com.sinch.sdk.domains.conversation.models.v1.messages.internal;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.sinch.sdk.domains.conversation.models.v1.ChannelRecipientIdentities;

/** Channel Identities */
@JsonDeserialize(builder = IdentifiedByFieldInternalImpl.Builder.class)
public interface IdentifiedByFieldInternal {

  /**
   * The identity as specified by the channel.
   *
   * @return identifiedBy
   */
  ChannelRecipientIdentities getIdentifiedBy();

  /**
   * Getting builder
   *
   * @return New Builder instance
   */
  static Builder builder() {
    return new IdentifiedByFieldInternalImpl.Builder();
  }

  /** Dedicated Builder */
  interface Builder {

    /**
     * see getter
     *
     * @param identifiedBy see getter
     * @return Current builder
     * @see #getIdentifiedBy
     */
    Builder setIdentifiedBy(ChannelRecipientIdentities identifiedBy);

    /**
     * Create instance
     *
     * @return The instance build with current builder values
     */
    IdentifiedByFieldInternal build();
  }
}
