/*
 * Mailgun API
 *
 * OpenAPI document version: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package com.sinch.sdk.domains.mailgun.models.v1.templates.request;

/** CreateTemplateRequest */
public interface CreateTemplateRequest {

  /**
   * Name of the template being stored. Supports utf-8 characters and name will be down cased.
   *
   * <p>Field is required
   *
   * @return name
   */
  String getName();

  /**
   * Description of the template being stored
   *
   * @return description
   */
  String getDescription();

  /**
   * Optional metadata field api user can indicate who created the template.
   *
   * @return createdBy
   */
  String getCreatedBy();

  /**
   * Getting builder
   *
   * @return New Builder instance
   */
  static Builder builder() {
    return new CreateTemplateRequestImpl.Builder();
  }

  /** Dedicated Builder */
  interface Builder {

    /**
     * see getter
     *
     * @param name see getter
     * @return Current builder
     * @see #getName
     */
    Builder setName(String name);

    /**
     * see getter
     *
     * @param description see getter
     * @return Current builder
     * @see #getDescription
     */
    Builder setDescription(String description);

    /**
     * see getter
     *
     * @param createdBy see getter
     * @return Current builder
     * @see #getCreatedBy
     */
    Builder setCreatedBy(String createdBy);

    /**
     * Create instance
     *
     * @return The instance build with current builder values
     */
    CreateTemplateRequest build();
  }
}
