/*
 * Numbers | Sinch
 *
 * OpenAPI document version: 1.0.3
 * Contact: Support@sinch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package com.sinch.sdk.domains.numbers.models.v1.numberorder.request;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.Map;

/** UpdateNumberOrderRegistrationRequest */
@JsonDeserialize(builder = UpdateNumberOrderRegistrationRequestImpl.Builder.class)
public interface UpdateNumberOrderRegistrationRequest {

  /**
   * Free-form JSON object representing registration data.
   *
   * @return data
   */
  Map<String, Object> getData();

  /**
   * Getting builder
   *
   * @return New Builder instance
   */
  static Builder builder() {
    return new UpdateNumberOrderRegistrationRequestImpl.Builder();
  }

  /** Dedicated Builder */
  interface Builder {

    /**
     * see getter
     *
     * @param data see getter
     * @return Current builder
     * @see #getData
     */
    Builder setData(Map<String, Object> data);

    /**
     * Create instance
     *
     * @return The instance build with current builder values
     */
    UpdateNumberOrderRegistrationRequest build();
  }
}
