/*
 * Mailgun API
 *
 * OpenAPI document version: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package com.sinch.sdk.domains.mailgun.models.v1.templates;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.time.Instant;

/** Template */
@JsonDeserialize(builder = TemplateImpl.Builder.class)
public interface Template {

  /**
   * Name of the template
   *
   * <p>Field is required
   *
   * @return name
   */
  String getName();

  /**
   * Description of the template
   *
   * @return description
   */
  String getDescription();

  /**
   * Creation date in RFC822 format
   *
   * @return createdAt
   * @readOnly <em>This field is returned by the server and cannot be modified</em>
   */
  Instant getCreatedAt();

  /**
   * Indicate who created the template
   *
   * @return createdBy
   */
  String getCreatedBy();

  /**
   * Template ID
   *
   * @return id
   * @readOnly <em>This field is returned by the server and cannot be modified</em>
   */
  String getId();

  /**
   * Getting builder
   *
   * @return New Builder instance
   */
  static Builder builder() {
    return new TemplateImpl.Builder();
  }

  /** Dedicated Builder */
  interface Builder {

    /**
     * see getter
     *
     * @param name see getter
     * @return Current builder
     * @see #getName
     */
    Builder setName(String name);

    /**
     * see getter
     *
     * @param description see getter
     * @return Current builder
     * @see #getDescription
     */
    Builder setDescription(String description);

    /**
     * see getter
     *
     * @param createdAt see getter
     * @return Current builder
     * @see #getCreatedAt
     * @readOnly <em>This field is returned by the server and cannot be modified</em>
     */
    Builder setCreatedAt(Instant createdAt);

    /**
     * see getter
     *
     * @param createdBy see getter
     * @return Current builder
     * @see #getCreatedBy
     */
    Builder setCreatedBy(String createdBy);

    /**
     * see getter
     *
     * @param id see getter
     * @return Current builder
     * @see #getId
     * @readOnly <em>This field is returned by the server and cannot be modified</em>
     */
    Builder setId(String id);

    /**
     * Create instance
     *
     * @return The instance build with current builder values
     */
    Template build();
  }
}
