/*
 * Conversation API | Sinch
 *
 * OpenAPI document version: 1.0
 * Contact: support@sinch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package com.sinch.sdk.domains.conversation.models.v1;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/** ChannelRecipientIdentity */
@JsonDeserialize(builder = ChannelRecipientIdentityImpl.Builder.class)
public interface ChannelRecipientIdentity {

  /**
   * Get channel
   *
   * @return channel
   */
  ConversationChannel getChannel();

  /**
   * The channel recipient identity.
   *
   * @return identity
   */
  String getIdentity();

  /**
   * Getting builder
   *
   * @return New Builder instance
   */
  static Builder builder() {
    return new ChannelRecipientIdentityImpl.Builder();
  }

  /** Dedicated Builder */
  interface Builder {

    /**
     * see getter
     *
     * @param channel see getter
     * @return Current builder
     * @see #getChannel
     */
    Builder setChannel(ConversationChannel channel);

    /**
     * see getter
     *
     * @param identity see getter
     * @return Current builder
     * @see #getIdentity
     */
    Builder setIdentity(String identity);

    /**
     * Create instance
     *
     * @return The instance build with current builder values
     */
    ChannelRecipientIdentity build();
  }
}
