/*
 * Conversation API | Sinch
 *
 * OpenAPI document version: 1.0
 * Contact: support@sinch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package com.sinch.sdk.domains.conversation.models.v1.messages.types.card;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.sinch.sdk.domains.conversation.models.v1.messages.types.choice.Choice;
import java.util.List;

/** Field containing a Card Message */
@JsonDeserialize(builder = CardMessageImpl.Builder.class)
public interface CardMessage
    extends com.sinch.sdk.domains.conversation.models.v1.messages.OmniMessageOverride,
        com.sinch.sdk.domains.conversation.models.v1.messages.AppMessageBody {

  /**
   * You may include choices in your Card Message. The number of choices is limited to 10.
   *
   * @return choices
   */
  List<Choice<?>> getChoices();

  /**
   * This is an optional description field that is displayed below the title on the card.
   *
   * @return description
   */
  String getDescription();

  /**
   * Get height
   *
   * @return height
   */
  CardHeight getHeight();

  /**
   * Get media
   *
   * @return media
   */
  CardMessageMedia getMedia();

  /**
   * The title of the card message.
   *
   * @return title
   */
  String getTitle();

  /**
   * Getting builder
   *
   * @return New Builder instance
   */
  static Builder builder() {
    return new CardMessageImpl.Builder();
  }

  /** Dedicated Builder */
  interface Builder {

    /**
     * see getter
     *
     * @param choices see getter
     * @return Current builder
     * @see #getChoices
     */
    Builder setChoices(List<Choice<?>> choices);

    /**
     * see getter
     *
     * @param description see getter
     * @return Current builder
     * @see #getDescription
     */
    Builder setDescription(String description);

    /**
     * see getter
     *
     * @param height see getter
     * @return Current builder
     * @see #getHeight
     */
    Builder setHeight(CardHeight height);

    /**
     * see getter
     *
     * @param media see getter
     * @return Current builder
     * @see #getMedia
     */
    Builder setMedia(CardMessageMedia media);

    /**
     * see getter
     *
     * @param title see getter
     * @return Current builder
     * @see #getTitle
     */
    Builder setTitle(String title);

    /**
     * Create instance
     *
     * @return The instance build with current builder values
     */
    CardMessage build();
  }
}
