/*
 * Conversation API | Sinch
 *
 * OpenAPI document version: 1.0
 * Contact: support@sinch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package com.sinch.sdk.domains.conversation.models.v1.messages.types.channelspecific.kakaotalk.carousel;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/** &quot;More&quot; button */
@JsonDeserialize(builder = CarouselTailImpl.Builder.class)
public interface CarouselTail {

  /**
   * URL opened on a mobile device
   *
   * <p>Field is required
   *
   * @return linkMo
   */
  String getLinkMo();

  /**
   * URL opened on a desktop device
   *
   * @return linkPc
   */
  String getLinkPc();

  /**
   * App link opened on an iOS device (e.g. <code>tel://PHONE_NUMBER</code>)
   *
   * @return schemeIos
   */
  String getSchemeIos();

  /**
   * App link opened on an Android device (e.g. <code>tel://PHONE_NUMBER</code>)
   *
   * @return schemeAndroid
   */
  String getSchemeAndroid();

  /**
   * Getting builder
   *
   * @return New Builder instance
   */
  static Builder builder() {
    return new CarouselTailImpl.Builder();
  }

  /** Dedicated Builder */
  interface Builder {

    /**
     * see getter
     *
     * @param linkMo see getter
     * @return Current builder
     * @see #getLinkMo
     */
    Builder setLinkMo(String linkMo);

    /**
     * see getter
     *
     * @param linkPc see getter
     * @return Current builder
     * @see #getLinkPc
     */
    Builder setLinkPc(String linkPc);

    /**
     * see getter
     *
     * @param schemeIos see getter
     * @return Current builder
     * @see #getSchemeIos
     */
    Builder setSchemeIos(String schemeIos);

    /**
     * see getter
     *
     * @param schemeAndroid see getter
     * @return Current builder
     * @see #getSchemeAndroid
     */
    Builder setSchemeAndroid(String schemeAndroid);

    /**
     * Create instance
     *
     * @return The instance build with current builder values
     */
    CarouselTail build();
  }
}
