/*
 * Numbers | Sinch
 *
 * OpenAPI document version: 1.0.3
 * Contact: Support@sinch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package com.sinch.sdk.domains.numbers.models.v1.response;

import com.sinch.sdk.core.http.HttpRequest;
import com.sinch.sdk.core.models.pagination.ListResponse;
import com.sinch.sdk.core.models.pagination.Page;
import com.sinch.sdk.domains.numbers.api.v1.adapters.ActiveNumberServiceImpl;
import com.sinch.sdk.domains.numbers.models.v1.ActiveNumber;
import com.sinch.sdk.domains.numbers.models.v1.request.ActiveNumbersListQueryParameters;
import java.util.Collection;
import java.util.Collections;
import java.util.NoSuchElementException;

/** Auto paginated response for list of ActiveNumber */
public class ActiveNumbersListResponse extends ListResponse<ActiveNumber> {

  private final Page<ActiveNumbersListQueryParameters, ActiveNumber, HttpRequest> page;
  private final ActiveNumberServiceImpl service;

  public ActiveNumbersListResponse(
      ActiveNumberServiceImpl service,
      Page<ActiveNumbersListQueryParameters, ActiveNumber, HttpRequest> page) {
    this.service = service;
    this.page = page;
  }

  @Override
  public boolean hasNextPage() {
    if (null == page.getNextPageToken() || null == getContent() || getContent().isEmpty()) {
      return false;
    }
    return true;
  }

  @Override
  public ActiveNumbersListResponse nextPage() {

    if (!hasNextPage()) {
      throw new NoSuchElementException("Reached the last page of the API response");
    }

    return service._getActiveNumbersPageAsListResponse(
        page.getParameters(), page.getNextPageToken());
  }

  @Override
  public Collection<ActiveNumber> getContent() {
    return page == null ? Collections.emptyList() : page.getEntities();
  }

  @Override
  public String toString() {
    return "ActiveNumbersListResponse {" + "page=" + page + '}';
  }
}
