/*
 * Numbers | Sinch
 *
 * OpenAPI document version: 1.0.2
 * Contact: Support@sinch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package com.sinch.sdk.domains.numbers.models.v1.response;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.sinch.sdk.domains.numbers.models.v1.Capability;
import com.sinch.sdk.domains.numbers.models.v1.Money;
import com.sinch.sdk.domains.numbers.models.v1.NumberType;
import java.util.List;

/**
 * The phone numbers that are available to be rented in the <a
 * href="https://dashboard.sinch.com/numbers/buy-numbers">Sinch Customer Dashboard</a> or via the
 * public numbers API.
 */
@JsonDeserialize(builder = AvailableNumberImpl.Builder.class)
public interface AvailableNumber {

  /**
   * The phone number in <a
   * href="https://community.sinch.com/t5/Glossary/E-164/ta-p/7537&quot;">E.164</a> format with
   * leading <code>+</code>.
   *
   * @return phoneNumber
   */
  String getPhoneNumber();

  /**
   * ISO 3166-1 alpha-2 country code of the phone number. Example: <code>US</code>, <code>GB</code>
   * or <code>SE</code>.
   *
   * @return regionCode
   */
  String getRegionCode();

  /**
   * Get type
   *
   * @return type
   */
  NumberType getType();

  /**
   * The capability of the number.
   *
   * @return capability
   */
  List<Capability> getCapability();

  /**
   * Get setupPrice
   *
   * @return setupPrice
   */
  Money getSetupPrice();

  /**
   * Get monthlyPrice
   *
   * @return monthlyPrice
   */
  Money getMonthlyPrice();

  /**
   * How often the recurring price is charged in months.
   *
   * @return paymentIntervalMonths
   */
  Integer getPaymentIntervalMonths();

  /**
   * Whether or not supplementary documentation will be required to complete the number rental.
   *
   * @return supportingDocumentationRequired
   */
  Boolean getSupportingDocumentationRequired();

  /**
   * Getting builder
   *
   * @return New Builder instance
   */
  static Builder builder() {
    return new AvailableNumberImpl.Builder();
  }

  /** Dedicated Builder */
  interface Builder {

    /**
     * see getter
     *
     * @param phoneNumber see getter
     * @return Current builder
     * @see #getPhoneNumber
     */
    Builder setPhoneNumber(String phoneNumber);

    /**
     * see getter
     *
     * @param regionCode see getter
     * @return Current builder
     * @see #getRegionCode
     */
    Builder setRegionCode(String regionCode);

    /**
     * see getter
     *
     * @param type see getter
     * @return Current builder
     * @see #getType
     */
    Builder setType(NumberType type);

    /**
     * see getter
     *
     * @param capability see getter
     * @return Current builder
     * @see #getCapability
     */
    Builder setCapability(List<Capability> capability);

    /**
     * see getter
     *
     * @param setupPrice see getter
     * @return Current builder
     * @see #getSetupPrice
     */
    Builder setSetupPrice(Money setupPrice);

    /**
     * see getter
     *
     * @param monthlyPrice see getter
     * @return Current builder
     * @see #getMonthlyPrice
     */
    Builder setMonthlyPrice(Money monthlyPrice);

    /**
     * see getter
     *
     * @param paymentIntervalMonths see getter
     * @return Current builder
     * @see #getPaymentIntervalMonths
     */
    Builder setPaymentIntervalMonths(Integer paymentIntervalMonths);

    /**
     * see getter
     *
     * @param supportingDocumentationRequired see getter
     * @return Current builder
     * @see #getSupportingDocumentationRequired
     */
    Builder setSupportingDocumentationRequired(Boolean supportingDocumentationRequired);

    /**
     * Create instance
     *
     * @return The instance build with current builder values
     */
    AvailableNumber build();
  }
}
