/*
 * Conversation API | Sinch
 *
 * OpenAPI document version: 1.0
 * Contact: support@sinch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package com.sinch.sdk.domains.conversation.models.v1.events.types;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/** Payment Status Update */
@JsonDeserialize(builder = PaymentStatusUpdateEventImpl.Builder.class)
public interface PaymentStatusUpdateEvent
    extends com.sinch.sdk.domains.conversation.models.v1.events.ContactMessageEvent {

  /**
   * This is the partner supplied ID to identify the order for payments
   *
   * @return referenceId
   */
  String getReferenceId();

  /**
   * Get paymentStatus
   *
   * @return paymentStatus
   */
  PaymentStatus getPaymentStatus();

  /**
   * Get paymentTransactionStatus
   *
   * @return paymentTransactionStatus
   */
  PaymentTransactionStatus getPaymentTransactionStatus();

  /**
   * Unique id of the transaction for which one of the transaction payment_transaction_status is
   * present in event.
   *
   * @return paymentTransactionId
   */
  String getPaymentTransactionId();

  /**
   * Getting builder
   *
   * @return New Builder instance
   */
  static Builder builder() {
    return new PaymentStatusUpdateEventImpl.Builder();
  }

  /** Dedicated Builder */
  interface Builder {

    /**
     * see getter
     *
     * @param referenceId see getter
     * @return Current builder
     * @see #getReferenceId
     */
    Builder setReferenceId(String referenceId);

    /**
     * see getter
     *
     * @param paymentStatus see getter
     * @return Current builder
     * @see #getPaymentStatus
     */
    Builder setPaymentStatus(PaymentStatus paymentStatus);

    /**
     * see getter
     *
     * @param paymentTransactionStatus see getter
     * @return Current builder
     * @see #getPaymentTransactionStatus
     */
    Builder setPaymentTransactionStatus(PaymentTransactionStatus paymentTransactionStatus);

    /**
     * see getter
     *
     * @param paymentTransactionId see getter
     * @return Current builder
     * @see #getPaymentTransactionId
     */
    Builder setPaymentTransactionId(String paymentTransactionId);

    /**
     * Create instance
     *
     * @return The instance build with current builder values
     */
    PaymentStatusUpdateEvent build();
  }
}
