/*
 * Conversation API | Sinch
 *
 * OpenAPI document version: 1.0
 * Contact: support@sinch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package com.sinch.sdk.domains.conversation.models.v1.events.types;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/** Short Link Activated */
@JsonDeserialize(builder = ShortLinkActivatedEventImpl.Builder.class)
public interface ShortLinkActivatedEvent
    extends com.sinch.sdk.domains.conversation.models.v1.events.ContactMessageEvent {

  /**
   * Refers to the payload previously configured to be sent in the postback.
   *
   * @return payload
   */
  String getPayload();

  /**
   * Only relevant for the Instagram channel.
   *
   * @return title
   */
  String getTitle();

  /**
   * The ref parameter from the shortlink the user visited.
   *
   * @return ref
   */
  String getRef();

  /**
   * Defaults to &quot;SHORTLINK&quot; for this type of event.
   *
   * @return source
   */
  String getSource();

  /**
   * The identifier for the referral. For Instagram and Messenger shortlinks, this is always set to
   * &quot;OPEN_THREAD&quot;.
   *
   * @return type
   */
  String getType();

  /**
   * Set to true if target channel's conversation thread already existed at the moment the shortlink
   * was visited. Set to false if a new conversation thread began when the shortlink was visited.
   *
   * @return existingThread
   */
  Boolean getExistingThread();

  /**
   * Getting builder
   *
   * @return New Builder instance
   */
  static Builder builder() {
    return new ShortLinkActivatedEventImpl.Builder();
  }

  /** Dedicated Builder */
  interface Builder {

    /**
     * see getter
     *
     * @param payload see getter
     * @return Current builder
     * @see #getPayload
     */
    Builder setPayload(String payload);

    /**
     * see getter
     *
     * @param title see getter
     * @return Current builder
     * @see #getTitle
     */
    Builder setTitle(String title);

    /**
     * see getter
     *
     * @param ref see getter
     * @return Current builder
     * @see #getRef
     */
    Builder setRef(String ref);

    /**
     * see getter
     *
     * @param source see getter
     * @return Current builder
     * @see #getSource
     */
    Builder setSource(String source);

    /**
     * see getter
     *
     * @param type see getter
     * @return Current builder
     * @see #getType
     */
    Builder setType(String type);

    /**
     * see getter
     *
     * @param existingThread see getter
     * @return Current builder
     * @see #getExistingThread
     */
    Builder setExistingThread(Boolean existingThread);

    /**
     * Create instance
     *
     * @return The instance build with current builder values
     */
    ShortLinkActivatedEvent build();
  }
}
