/*
 * Verification | Sinch
 * Verify users with SMS, flash calls (missed calls), a regular call, or data verification.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@sinch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sinch.sdk.domains.verification.models.v1.webhooks;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/** declaration */
@JsonDeserialize(builder = CalloutRequestEventResponseImpl.Builder.class)
public interface CalloutRequestEventResponse {

  /**
   * Get action
   *
   * @return action
   */
  VerificationEventResponseAction getAction();

  /**
   * Get callout
   *
   * @return callout
   */
  CalloutRequestEventResponseCalloutContent getCallout();

  /**
   * Getting builder
   *
   * @return New Builder instance
   */
  static Builder builder() {
    return new CalloutRequestEventResponseImpl.Builder();
  }

  /** Dedicated Builder */
  interface Builder {

    /**
     * see getter
     *
     * @param action see getter
     * @return Current builder
     * @see #getAction
     */
    Builder setAction(VerificationEventResponseAction action);

    /**
     * see getter
     *
     * @param callout see getter
     * @return Current builder
     * @see #getCallout
     */
    Builder setCallout(CalloutRequestEventResponseCalloutContent callout);

    /**
     * Create instance
     *
     * @return The instance build with current builder values
     */
    CalloutRequestEventResponse build();
  }
}
