# springboot related config file

logging:
  level:
    com: INFO

server:
    port: 8090

credentials:
  application:
      key: 191585b9-6d7a-4660-8910-e5587fcce67f
      secret: CEEvSif/2EqrJI5bUufERA==

voice:
  controller-path: /voice
