/*
 * Conversation API | Sinch
 * Send and receive messages globally over SMS, RCS, WhatsApp, Viber Business, Facebook messenger and other popular channels using the Sinch Conversation API.  The Conversation API endpoint uses built-in transcoding to give you the power of conversation across all supported channels and, if required, full control over channel specific features.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@sinch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sinch.sdk.domains.conversation.models.dto.v1;

import com.fasterxml.jackson.annotation.JsonFilter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/** CommentReplyEventDto */
@JsonPropertyOrder({CommentReplyEventDto.JSON_PROPERTY_COMMENT_REPLY_EVENT})
@JsonFilter("uninitializedFilter")
@JsonInclude(value = JsonInclude.Include.CUSTOM)
public class CommentReplyEventDto {
  private static final long serialVersionUID = 1L;
  public static final String JSON_PROPERTY_COMMENT_REPLY_EVENT = "comment_reply_event";
  private CommentReplyEventDto commentReplyEvent;
  private boolean commentReplyEventDefined = false;

  public CommentReplyEventDto() {}

  public CommentReplyEventDto commentReplyEvent(CommentReplyEventDto commentReplyEvent) {
    this.commentReplyEvent = commentReplyEvent;
    this.commentReplyEventDefined = true;
    return this;
  }

  /**
   * Get commentReplyEvent
   *
   * @return commentReplyEvent
   */
  @JsonProperty(JSON_PROPERTY_COMMENT_REPLY_EVENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CommentReplyEventDto getCommentReplyEvent() {
    return commentReplyEvent;
  }

  @JsonIgnore
  public boolean getCommentReplyEventDefined() {
    return commentReplyEventDefined;
  }

  @JsonProperty(JSON_PROPERTY_COMMENT_REPLY_EVENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommentReplyEvent(CommentReplyEventDto commentReplyEvent) {
    this.commentReplyEvent = commentReplyEvent;
    this.commentReplyEventDefined = true;
  }

  /** Return true if this comment_reply_event object is equal to o. */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommentReplyEventDto commentReplyEvent = (CommentReplyEventDto) o;
    return Objects.equals(this.commentReplyEvent, commentReplyEvent.commentReplyEvent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commentReplyEvent);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommentReplyEventDto {\n");
    sb.append("    commentReplyEvent: ").append(toIndentedString(commentReplyEvent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
