/*
 * Conversation API | Sinch
 * Send and receive messages globally over SMS, RCS, WhatsApp, Viber Business, Facebook messenger and other popular channels using the Sinch Conversation API.  The Conversation API endpoint uses built-in transcoding to give you the power of conversation across all supported channels and, if required, full control over channel specific features.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@sinch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sinch.sdk.domains.conversation.models.dto.v1;

import com.fasterxml.jackson.annotation.JsonFilter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/**
 * The retention policy configured for the app. For more information about retention policies, see
 * [Retention Policy](/docs/conversation/keyconcepts/#retention-policy).
 */
@JsonPropertyOrder({
  RetentionPolicyDto.JSON_PROPERTY_RETENTION_TYPE,
  RetentionPolicyDto.JSON_PROPERTY_TTL_DAYS
})
@JsonFilter("uninitializedFilter")
@JsonInclude(value = JsonInclude.Include.CUSTOM)
public class RetentionPolicyDto {
  public static final String JSON_PROPERTY_RETENTION_TYPE = "retention_type";
  private RetentionPolicyTypeDto retentionType;
  private boolean retentionTypeDefined = false;

  public static final String JSON_PROPERTY_TTL_DAYS = "ttl_days";
  private Long ttlDays;
  private boolean ttlDaysDefined = false;

  public RetentionPolicyDto() {}

  public RetentionPolicyDto retentionType(RetentionPolicyTypeDto retentionType) {
    this.retentionType = retentionType;
    this.retentionTypeDefined = true;
    return this;
  }

  /**
   * Get retentionType
   *
   * @return retentionType
   */
  @JsonProperty(JSON_PROPERTY_RETENTION_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public RetentionPolicyTypeDto getRetentionType() {
    return retentionType;
  }

  @JsonIgnore
  public boolean getRetentionTypeDefined() {
    return retentionTypeDefined;
  }

  @JsonProperty(JSON_PROPERTY_RETENTION_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRetentionType(RetentionPolicyTypeDto retentionType) {
    this.retentionType = retentionType;
    this.retentionTypeDefined = true;
  }

  public RetentionPolicyDto ttlDays(Long ttlDays) {
    this.ttlDays = ttlDays;
    this.ttlDaysDefined = true;
    return this;
  }

  /**
   * Optional. The days before a message or conversation is eligible for deletion. Default value is
   * 180. The ttl_days value has no effect when retention_type is
   * &#x60;PERSIST_RETENTION_POLICY&#x60;. The valid values for this field are [1 - 3650]. Note that
   * retention cleanup job runs once every twenty-four hours which can lead to delay i.e., messages
   * and conversations are not deleted on the minute they become eligible for deletion.
   *
   * @return ttlDays
   */
  @JsonProperty(JSON_PROPERTY_TTL_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getTtlDays() {
    return ttlDays;
  }

  @JsonIgnore
  public boolean getTtlDaysDefined() {
    return ttlDaysDefined;
  }

  @JsonProperty(JSON_PROPERTY_TTL_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTtlDays(Long ttlDays) {
    this.ttlDays = ttlDays;
    this.ttlDaysDefined = true;
  }

  /** Return true if this RetentionPolicy object is equal to o. */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RetentionPolicyDto retentionPolicy = (RetentionPolicyDto) o;
    return Objects.equals(this.retentionType, retentionPolicy.retentionType)
        && Objects.equals(this.ttlDays, retentionPolicy.ttlDays);
  }

  @Override
  public int hashCode() {
    return Objects.hash(retentionType, ttlDays);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RetentionPolicyDto {\n");
    sb.append("    retentionType: ").append(toIndentedString(retentionType)).append("\n");
    sb.append("    ttlDays: ").append(toIndentedString(ttlDays)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
