/*
 * Conversation API | Sinch
 * Send and receive messages globally over SMS, RCS, WhatsApp, Viber Business, Facebook messenger and other popular channels using the Sinch Conversation API.  The Conversation API endpoint uses built-in transcoding to give you the power of conversation across all supported channels and, if required, full control over channel specific features.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@sinch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sinch.sdk.domains.conversation.models.dto.v1;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFilter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Map;
import java.util.Objects;

/** TranscodeMessageResponseDto */
@JsonPropertyOrder({TranscodeMessageResponseDto.JSON_PROPERTY_TRANSCODED_MESSAGE})
@JsonFilter("uninitializedFilter")
@JsonInclude(value = JsonInclude.Include.CUSTOM)
public class TranscodeMessageResponseDto {
  private static final long serialVersionUID = 1L;
  public static final String JSON_PROPERTY_TRANSCODED_MESSAGE = "transcoded_message";
  private Map<String, String> transcodedMessage;
  private boolean transcodedMessageDefined = false;

  public TranscodeMessageResponseDto() {}

  @JsonCreator
  public TranscodeMessageResponseDto(
      @JsonProperty(JSON_PROPERTY_TRANSCODED_MESSAGE) Map<String, String> transcodedMessage) {
    this();
    this.transcodedMessage = transcodedMessage;
    this.transcodedMessageDefined = true;
  }

  /**
   * The transcoded message for the different channels. The keys in the map correspond to channel
   * names, as defined by the type ConversationChannel.
   *
   * @return transcodedMessage
   */
  @JsonProperty(JSON_PROPERTY_TRANSCODED_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, String> getTranscodedMessage() {
    return transcodedMessage;
  }

  @JsonIgnore
  public boolean getTranscodedMessageDefined() {
    return transcodedMessageDefined;
  }

  /** Return true if this TranscodeMessageResponse object is equal to o. */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TranscodeMessageResponseDto transcodeMessageResponse = (TranscodeMessageResponseDto) o;
    return Objects.equals(this.transcodedMessage, transcodeMessageResponse.transcodedMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transcodedMessage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TranscodeMessageResponseDto {\n");
    sb.append("    transcodedMessage: ").append(toIndentedString(transcodedMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
