/*
 * Conversation API | Sinch
 *
 * OpenAPI document version: 1.0
 * Contact: support@sinch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package com.sinch.sdk.domains.conversation.models.v1.messages.types.contactinfo;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/** A URL/website */
@JsonDeserialize(builder = UrlInfoImpl.Builder.class)
public interface UrlInfo {

  /**
   * The URL to be referenced
   *
   * <p>Field is required
   *
   * @return url
   */
  String getUrl();

  /**
   * Optional. URL type, e.g. Org or Social
   *
   * @return type
   */
  String getType();

  /**
   * Getting builder
   *
   * @return New Builder instance
   */
  static Builder builder() {
    return new UrlInfoImpl.Builder();
  }

  /** Dedicated Builder */
  interface Builder {

    /**
     * see getter
     *
     * @param url see getter
     * @return Current builder
     * @see #getUrl
     */
    Builder setUrl(String url);

    /**
     * see getter
     *
     * @param type see getter
     * @return Current builder
     * @see #getType
     */
    Builder setType(String type);

    /**
     * Create instance
     *
     * @return The instance build with current builder values
     */
    UrlInfo build();
  }
}
