/*
 * Conversation API | Sinch
 * Send and receive messages globally over SMS, RCS, WhatsApp, Viber Business, Facebook messenger and other popular channels using the Sinch Conversation API.  The Conversation API endpoint uses built-in transcoding to give you the power of conversation across all supported channels and, if required, full control over channel specific features.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@sinch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sinch.sdk.domains.conversation.models.v1.messages;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/** declaration */
@JsonDeserialize(builder = CoordinatesImpl.Builder.class)
public interface Coordinates {

  /**
   * The latitude.
   *
   * @return latitude
   */
  Float getLatitude();

  /**
   * The longitude.
   *
   * @return longitude
   */
  Float getLongitude();

  /**
   * Getting builder
   *
   * @return New Builder instance
   */
  static Builder builder() {
    return new CoordinatesImpl.Builder();
  }

  /** Dedicated Builder */
  interface Builder {

    /**
     * see getter
     *
     * @param latitude see getter
     * @return Current builder
     * @see #getLatitude
     */
    Builder setLatitude(Float latitude);

    /**
     * see getter
     *
     * @param longitude see getter
     * @return Current builder
     * @see #getLongitude
     */
    Builder setLongitude(Float longitude);

    /**
     * Create instance
     *
     * @return The instance build with current builder values
     */
    Coordinates build();
  }
}
