/*
 * Mailgun API
 *
 * OpenAPI document version: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package com.sinch.sdk.domains.mailgun.models.v1.emails.request;

/** TemplateProperties */
public interface TemplateProperties {

  /**
   * Render template in case of template sending
   *
   * @return text
   */
  Boolean getText();

  /**
   * Render a specific version of the given template instead of the latest version. <code>o:template
   * </code> option must also be provided.
   *
   * @return version
   */
  String getVersion();

  /**
   * A valid JSON-encoded dictionary used as the input for template variable expansion. See <a
   * href="https://documentation.mailgun.com/docs/mailgun/user-manual/sending-messages/#templates">Templates</a>
   * for more information
   *
   * @return variables
   */
  String getVariables();

  /**
   * Getting builder
   *
   * @return New Builder instance
   */
  static Builder builder() {
    return new TemplatePropertiesImpl.Builder();
  }

  /** Dedicated Builder */
  interface Builder {

    /**
     * see getter
     *
     * @param text see getter
     * @return Current builder
     * @see #getText
     */
    Builder setText(Boolean text);

    /**
     * see getter
     *
     * @param version see getter
     * @return Current builder
     * @see #getVersion
     */
    Builder setVersion(String version);

    /**
     * see getter
     *
     * @param variables see getter
     * @return Current builder
     * @see #getVariables
     */
    Builder setVariables(String variables);

    /**
     * Create instance
     *
     * @return The instance build with current builder values
     */
    TemplateProperties build();
  }
}
