# springboot related config file

logging:
  level:
    com: INFO

server:
    port: 8090

credentials:
  project-id: b8bae3c6-e7df-422b-9401-8ae3ee3e0add
  key-id: e78d485b-e3b3-4578-88e1-4c5983428e21
  key-secret: xvYSbS5TPex1IXknEUCR_NyiAN

