/*
 * Conversation API | Sinch
 *
 * OpenAPI document version: 1.0
 * Contact: support@sinch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package com.sinch.sdk.domains.conversation.models.v1.conversation.internal;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.sinch.sdk.domains.conversation.models.v1.conversation.response.ConversationRecentMessage;
import java.util.List;

/** ListRecentConversationsResponseInternal */
@JsonDeserialize(builder = ListRecentConversationsResponseInternalImpl.Builder.class)
public interface ListRecentConversationsResponseInternal {

  /**
   * List of recent conversations
   *
   * @return conversations
   */
  List<ConversationRecentMessage> getConversations();

  /**
   * Token that should be included in the next request to fetch the next page.
   *
   * @return nextPageToken
   */
  String getNextPageToken();

  /**
   * Get totalSize
   *
   * @return totalSize
   */
  Integer getTotalSize();

  /**
   * Getting builder
   *
   * @return New Builder instance
   */
  static Builder builder() {
    return new ListRecentConversationsResponseInternalImpl.Builder();
  }

  /** Dedicated Builder */
  interface Builder {

    /**
     * see getter
     *
     * @param conversations see getter
     * @return Current builder
     * @see #getConversations
     */
    Builder setConversations(List<ConversationRecentMessage> conversations);

    /**
     * see getter
     *
     * @param nextPageToken see getter
     * @return Current builder
     * @see #getNextPageToken
     */
    Builder setNextPageToken(String nextPageToken);

    /**
     * see getter
     *
     * @param totalSize see getter
     * @return Current builder
     * @see #getTotalSize
     */
    Builder setTotalSize(Integer totalSize);

    /**
     * Create instance
     *
     * @return The instance build with current builder values
     */
    ListRecentConversationsResponseInternal build();
  }
}
