/*
 * Conversation API | Sinch
 *
 * OpenAPI document version: 1.0
 * Contact: support@sinch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package com.sinch.sdk.domains.conversation.models.v1.messages.types.internal;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.sinch.sdk.domains.conversation.models.v1.ConversationChannel;
import com.sinch.sdk.domains.conversation.models.v1.internal.TemplateReferenceInternal;
import java.util.Map;

/** Template Message */
@JsonDeserialize(builder = TemplateMessageInternalImpl.Builder.class)
public interface TemplateMessageInternal {

  /**
   * Optional. Channel specific template reference with parameters per channel. The channel template
   * if exists overrides the omnichannel template. At least one of <code>channel_template</code> or
   * <code>omni_template</code> needs to be present. The key in the map must point to a valid
   * conversation channel as defined by the enum ConversationChannel.
   *
   * @return channelTemplate
   */
  Map<ConversationChannel, TemplateReferenceInternal> getChannelTemplate();

  /**
   * Get omniTemplate
   *
   * @return omniTemplate
   */
  TemplateReferenceInternal getOmniTemplate();

  /**
   * Getting builder
   *
   * @return New Builder instance
   */
  static Builder builder() {
    return new TemplateMessageInternalImpl.Builder();
  }

  /** Dedicated Builder */
  interface Builder {

    /**
     * see getter
     *
     * @param channelTemplate see getter
     * @return Current builder
     * @see #getChannelTemplate
     */
    Builder setChannelTemplate(Map<ConversationChannel, TemplateReferenceInternal> channelTemplate);

    /**
     * see getter
     *
     * @param omniTemplate see getter
     * @return Current builder
     * @see #getOmniTemplate
     */
    Builder setOmniTemplate(TemplateReferenceInternal omniTemplate);

    /**
     * Create instance
     *
     * @return The instance build with current builder values
     */
    TemplateMessageInternal build();
  }
}
