/*
 * Voice API | Sinch
 * The Voice API exposes calling- and conference-related functionality in the Sinch Voice Platform.
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@sinch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sinch.sdk.domains.voice.models.dto.v1;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFilter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Objects;

/** GetCallResponseObjDto */
@JsonPropertyOrder({
  GetCallResponseObjDto.JSON_PROPERTY_FROM,
  GetCallResponseObjDto.JSON_PROPERTY_TO,
  GetCallResponseObjDto.JSON_PROPERTY_DOMAIN,
  GetCallResponseObjDto.JSON_PROPERTY_CALL_ID,
  GetCallResponseObjDto.JSON_PROPERTY_DURATION,
  GetCallResponseObjDto.JSON_PROPERTY_STATUS,
  GetCallResponseObjDto.JSON_PROPERTY_RESULT,
  GetCallResponseObjDto.JSON_PROPERTY_REASON,
  GetCallResponseObjDto.JSON_PROPERTY_TIMESTAMP,
  GetCallResponseObjDto.JSON_PROPERTY_CUSTOM,
  GetCallResponseObjDto.JSON_PROPERTY_USER_RATE,
  GetCallResponseObjDto.JSON_PROPERTY_DEBIT
})
@JsonFilter("uninitializedFilter")
@JsonInclude(value = JsonInclude.Include.CUSTOM)
public class GetCallResponseObjDto {
  public static final String JSON_PROPERTY_FROM = "from";
  private String from;
  private boolean fromDefined = false;

  public static final String JSON_PROPERTY_TO = "to";
  private String to;
  private boolean toDefined = false;

  /** Must be &#x60;pstn&#x60; for PSTN. */
  public enum DomainEnum {
    PSTN("pstn"),

    UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

    private String value;

    DomainEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DomainEnum fromValue(String value) {
      for (DomainEnum b : DomainEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }
  }

  public static final String JSON_PROPERTY_DOMAIN = "domain";
  private String domain;
  private boolean domainDefined = false;

  public static final String JSON_PROPERTY_CALL_ID = "callId";
  private String callId;
  private boolean callIdDefined = false;

  public static final String JSON_PROPERTY_DURATION = "duration";
  private Integer duration;
  private boolean durationDefined = false;

  /** The status of the call. Either &#x60;ONGOING&#x60; or &#x60;FINAL&#x60; */
  public enum StatusEnum {
    ONGOING("ONGOING"),

    FINAL("FINAL"),

    UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  private String status;
  private boolean statusDefined = false;

  /** Contains the result of a call. */
  public enum ResultEnum {
    N_A("N/A"),

    ANSWERED("ANSWERED"),

    BUSY("BUSY"),

    NOANSWER("NOANSWER"),

    FAILED("FAILED"),

    UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

    private String value;

    ResultEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ResultEnum fromValue(String value) {
      for (ResultEnum b : ResultEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }
  }

  public static final String JSON_PROPERTY_RESULT = "result";
  private String result;
  private boolean resultDefined = false;

  /** Contains the reason why a call ended. */
  public enum ReasonEnum {
    N_A("N/A"),

    TIMEOUT("TIMEOUT"),

    CALLERHANGUP("CALLERHANGUP"),

    CALLEEHANGUP("CALLEEHANGUP"),

    BLOCKED("BLOCKED"),

    NOCREDITPARTNER("NOCREDITPARTNER"),

    MANAGERHANGUP("MANAGERHANGUP"),

    CANCEL("CANCEL"),

    GENERALERROR("GENERALERROR"),

    UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

    private String value;

    ReasonEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ReasonEnum fromValue(String value) {
      for (ReasonEnum b : ReasonEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }
  }

  public static final String JSON_PROPERTY_REASON = "reason";
  private String reason;
  private boolean reasonDefined = false;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  private OffsetDateTime timestamp;
  private boolean timestampDefined = false;

  public static final String JSON_PROPERTY_CUSTOM = "custom";
  private Object custom;
  private boolean customDefined = false;

  public static final String JSON_PROPERTY_USER_RATE = "userRate";
  private String userRate;
  private boolean userRateDefined = false;

  public static final String JSON_PROPERTY_DEBIT = "debit";
  private String debit;
  private boolean debitDefined = false;

  public GetCallResponseObjDto() {}

  public GetCallResponseObjDto from(String from) {
    this.from = from;
    this.fromDefined = true;
    return this;
  }

  /**
   * Contains the caller information.
   *
   * @return from
   */
  @JsonProperty(JSON_PROPERTY_FROM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFrom() {
    return from;
  }

  @JsonIgnore
  public boolean getFromDefined() {
    return fromDefined;
  }

  @JsonProperty(JSON_PROPERTY_FROM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFrom(String from) {
    this.from = from;
    this.fromDefined = true;
  }

  public GetCallResponseObjDto to(String to) {
    this.to = to;
    this.toDefined = true;
    return this;
  }

  /**
   * Contains the callee information.
   *
   * @return to
   */
  @JsonProperty(JSON_PROPERTY_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTo() {
    return to;
  }

  @JsonIgnore
  public boolean getToDefined() {
    return toDefined;
  }

  @JsonProperty(JSON_PROPERTY_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTo(String to) {
    this.to = to;
    this.toDefined = true;
  }

  public GetCallResponseObjDto domain(String domain) {
    this.domain = domain;
    this.domainDefined = true;
    return this;
  }

  /**
   * Must be &#x60;pstn&#x60; for PSTN.
   *
   * @return domain
   */
  @JsonProperty(JSON_PROPERTY_DOMAIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDomain() {
    return domain;
  }

  @JsonIgnore
  public boolean getDomainDefined() {
    return domainDefined;
  }

  @JsonProperty(JSON_PROPERTY_DOMAIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDomain(String domain) {
    this.domain = domain;
    this.domainDefined = true;
  }

  public GetCallResponseObjDto callId(String callId) {
    this.callId = callId;
    this.callIdDefined = true;
    return this;
  }

  /**
   * The unique identifier of the call.
   *
   * @return callId
   */
  @JsonProperty(JSON_PROPERTY_CALL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCallId() {
    return callId;
  }

  @JsonIgnore
  public boolean getCallIdDefined() {
    return callIdDefined;
  }

  @JsonProperty(JSON_PROPERTY_CALL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCallId(String callId) {
    this.callId = callId;
    this.callIdDefined = true;
  }

  public GetCallResponseObjDto duration(Integer duration) {
    this.duration = duration;
    this.durationDefined = true;
    return this;
  }

  /**
   * The duration of the call in seconds.
   *
   * @return duration
   */
  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getDuration() {
    return duration;
  }

  @JsonIgnore
  public boolean getDurationDefined() {
    return durationDefined;
  }

  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDuration(Integer duration) {
    this.duration = duration;
    this.durationDefined = true;
  }

  public GetCallResponseObjDto status(String status) {
    this.status = status;
    this.statusDefined = true;
    return this;
  }

  /**
   * The status of the call. Either &#x60;ONGOING&#x60; or &#x60;FINAL&#x60;
   *
   * @return status
   */
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStatus() {
    return status;
  }

  @JsonIgnore
  public boolean getStatusDefined() {
    return statusDefined;
  }

  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(String status) {
    this.status = status;
    this.statusDefined = true;
  }

  public GetCallResponseObjDto result(String result) {
    this.result = result;
    this.resultDefined = true;
    return this;
  }

  /**
   * Contains the result of a call.
   *
   * @return result
   */
  @JsonProperty(JSON_PROPERTY_RESULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getResult() {
    return result;
  }

  @JsonIgnore
  public boolean getResultDefined() {
    return resultDefined;
  }

  @JsonProperty(JSON_PROPERTY_RESULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResult(String result) {
    this.result = result;
    this.resultDefined = true;
  }

  public GetCallResponseObjDto reason(String reason) {
    this.reason = reason;
    this.reasonDefined = true;
    return this;
  }

  /**
   * Contains the reason why a call ended.
   *
   * @return reason
   */
  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getReason() {
    return reason;
  }

  @JsonIgnore
  public boolean getReasonDefined() {
    return reasonDefined;
  }

  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReason(String reason) {
    this.reason = reason;
    this.reasonDefined = true;
  }

  public GetCallResponseObjDto timestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    this.timestampDefined = true;
    return this;
  }

  /**
   * The date and time of the call.
   *
   * @return timestamp
   */
  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  @JsonIgnore
  public boolean getTimestampDefined() {
    return timestampDefined;
  }

  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    this.timestampDefined = true;
  }

  public GetCallResponseObjDto custom(Object custom) {
    this.custom = custom;
    this.customDefined = true;
    return this;
  }

  /**
   * An object that can be used to pass custom information related to the call.
   *
   * @return custom
   */
  @JsonProperty(JSON_PROPERTY_CUSTOM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Object getCustom() {
    return custom;
  }

  @JsonIgnore
  public boolean getCustomDefined() {
    return customDefined;
  }

  @JsonProperty(JSON_PROPERTY_CUSTOM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustom(Object custom) {
    this.custom = custom;
    this.customDefined = true;
  }

  public GetCallResponseObjDto userRate(String userRate) {
    this.userRate = userRate;
    this.userRateDefined = true;
    return this;
  }

  /**
   * The rate per minute that was charged for the call.
   *
   * @return userRate
   */
  @JsonProperty(JSON_PROPERTY_USER_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUserRate() {
    return userRate;
  }

  @JsonIgnore
  public boolean getUserRateDefined() {
    return userRateDefined;
  }

  @JsonProperty(JSON_PROPERTY_USER_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserRate(String userRate) {
    this.userRate = userRate;
    this.userRateDefined = true;
  }

  public GetCallResponseObjDto debit(String debit) {
    this.debit = debit;
    this.debitDefined = true;
    return this;
  }

  /**
   * The total amount charged for the call.
   *
   * @return debit
   */
  @JsonProperty(JSON_PROPERTY_DEBIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDebit() {
    return debit;
  }

  @JsonIgnore
  public boolean getDebitDefined() {
    return debitDefined;
  }

  @JsonProperty(JSON_PROPERTY_DEBIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDebit(String debit) {
    this.debit = debit;
    this.debitDefined = true;
  }

  /** Return true if this getCallResponseObj object is equal to o. */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCallResponseObjDto getCallResponseObj = (GetCallResponseObjDto) o;
    return Objects.equals(this.from, getCallResponseObj.from)
        && Objects.equals(this.to, getCallResponseObj.to)
        && Objects.equals(this.domain, getCallResponseObj.domain)
        && Objects.equals(this.callId, getCallResponseObj.callId)
        && Objects.equals(this.duration, getCallResponseObj.duration)
        && Objects.equals(this.status, getCallResponseObj.status)
        && Objects.equals(this.result, getCallResponseObj.result)
        && Objects.equals(this.reason, getCallResponseObj.reason)
        && Objects.equals(this.timestamp, getCallResponseObj.timestamp)
        && Objects.equals(this.custom, getCallResponseObj.custom)
        && Objects.equals(this.userRate, getCallResponseObj.userRate)
        && Objects.equals(this.debit, getCallResponseObj.debit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        from, to, domain, callId, duration, status, result, reason, timestamp, custom, userRate,
        debit);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCallResponseObjDto {\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    callId: ").append(toIndentedString(callId)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    custom: ").append(toIndentedString(custom)).append("\n");
    sb.append("    userRate: ").append(toIndentedString(userRate)).append("\n");
    sb.append("    debit: ").append(toIndentedString(debit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
