/*
 * Voice API | Sinch
 * The Voice API exposes calling- and conference-related functionality in the Sinch Voice Platform.
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@sinch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sinch.sdk.domains.voice.models.dto.v1;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/** GetConferenceInfoResponseParticipantsInnerDto */
@JsonPropertyOrder({
  GetConferenceInfoResponseParticipantsInnerDto.JSON_PROPERTY_CLI,
  GetConferenceInfoResponseParticipantsInnerDto.JSON_PROPERTY_ID,
  GetConferenceInfoResponseParticipantsInnerDto.JSON_PROPERTY_DURATION,
  GetConferenceInfoResponseParticipantsInnerDto.JSON_PROPERTY_MUTED,
  GetConferenceInfoResponseParticipantsInnerDto.JSON_PROPERTY_ONHOLD
})
// @javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class GetConferenceInfoResponseParticipantsInnerDto {
  public static final String JSON_PROPERTY_CLI = "cli";
  private String cli;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_DURATION = "duration";
  private Integer duration;

  public static final String JSON_PROPERTY_MUTED = "muted";
  private Boolean muted;

  public static final String JSON_PROPERTY_ONHOLD = "onhold";
  private Boolean onhold;

  public GetConferenceInfoResponseParticipantsInnerDto() {}

  public GetConferenceInfoResponseParticipantsInnerDto cli(String cli) {
    this.cli = cli;
    return this;
  }

  /**
   * The phone number of the PSTN participant that was connected in the conference, or whatever was
   * passed as CLI for data originated/terminated calls.
   *
   * @return cli
   */
  @JsonProperty(JSON_PROPERTY_CLI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCli() {
    return cli;
  }

  @JsonProperty(JSON_PROPERTY_CLI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCli(String cli) {
    this.cli = cli;
  }

  public GetConferenceInfoResponseParticipantsInnerDto id(String id) {
    this.id = id;
    return this;
  }

  /**
   * The callId of the call leg that the participant joined the conference.
   *
   * @return id
   */
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getId() {
    return id;
  }

  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }

  public GetConferenceInfoResponseParticipantsInnerDto duration(Integer duration) {
    this.duration = duration;
    return this;
  }

  /**
   * The number of seconds that the participant has been connected to the conference.
   *
   * @return duration
   */
  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getDuration() {
    return duration;
  }

  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDuration(Integer duration) {
    this.duration = duration;
  }

  public GetConferenceInfoResponseParticipantsInnerDto muted(Boolean muted) {
    this.muted = muted;
    return this;
  }

  /**
   * Get muted
   *
   * @return muted
   */
  @JsonProperty(JSON_PROPERTY_MUTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getMuted() {
    return muted;
  }

  @JsonProperty(JSON_PROPERTY_MUTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMuted(Boolean muted) {
    this.muted = muted;
  }

  public GetConferenceInfoResponseParticipantsInnerDto onhold(Boolean onhold) {
    this.onhold = onhold;
    return this;
  }

  /**
   * Get onhold
   *
   * @return onhold
   */
  @JsonProperty(JSON_PROPERTY_ONHOLD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getOnhold() {
    return onhold;
  }

  @JsonProperty(JSON_PROPERTY_ONHOLD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOnhold(Boolean onhold) {
    this.onhold = onhold;
  }

  /** Return true if this getConferenceInfoResponse_participants_inner object is equal to o. */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetConferenceInfoResponseParticipantsInnerDto getConferenceInfoResponseParticipantsInner =
        (GetConferenceInfoResponseParticipantsInnerDto) o;
    return Objects.equals(this.cli, getConferenceInfoResponseParticipantsInner.cli)
        && Objects.equals(this.id, getConferenceInfoResponseParticipantsInner.id)
        && Objects.equals(this.duration, getConferenceInfoResponseParticipantsInner.duration)
        && Objects.equals(this.muted, getConferenceInfoResponseParticipantsInner.muted)
        && Objects.equals(this.onhold, getConferenceInfoResponseParticipantsInner.onhold);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cli, id, duration, muted, onhold);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetConferenceInfoResponseParticipantsInnerDto {\n");
    sb.append("    cli: ").append(toIndentedString(cli)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    muted: ").append(toIndentedString(muted)).append("\n");
    sb.append("    onhold: ").append(toIndentedString(onhold)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
