name: Publish javadoc
run-name: Trigger a PR onto documentation repo to publish javadoc artifact
on:
  workflow_dispatch:
    inputs:
      SEMVER:
        description: "Javadoc Version number to be published (use semver semantic: 'X.Y.Z'). File will be downloaded from https://repo1.maven.org/maven2/com/sinch/sdk/sinch-sdk-java/X.Y.Z"
        required: true

jobs:
  trigger-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: grep "${{ github.actor }}" .github/CODEOWNERS && curl --request POST --form token=${{ secrets.SINCH_SDK_JAVA_PUBLISH_JAVADOC_TOKEN }} --form ref=development --form "variables[TRIGGER_JOB]"="sinch-sdk-java-publish-javadoc" --form "variables[SEMVER]"="${{ github.event.inputs.SEMVER }}" "${{ secrets.JAVADOC_PUBLISH_URL}}"
